name: Show

on:
  - push

jobs:
  show:
    name: Show

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update packages
        if: false
        run: sudo apt update -y

      - name: Install podman
        if: false
        run: sudo apt install -y podman

      - name: 'Build image: ubuntu'
        run: docker build . --file ubuntu-with-updated-packages.Dockerfile

      - name: 'Build image: cowsay'
        run: docker build . --file cowsay.Dockerfile --tag cowsay:latest

      - name: Cow greets
        run: docker run --rm cowsay:latest cowsay 'Hello from GitHub Workflows'
